// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Header is an autogenerated mock type for the Header type
type Header struct {
	mock.Mock
}

// Add provides a mock function with given fields: key, value
func (_m *Header) Add(key string, value string) {
	_m.Called(key, value)
}

// NewHeader creates a new instance of Header. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHeader(t interface {
	mock.TestingT
	Cleanup(func())
}) *Header {
	mock := &Header{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
